apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metrics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: metrics
    spec:
      containers:
      - name: metrics
        image: us.gcr.io/replay-gaming/go-metrics:SOMESHA
        env:
        - name: METRICS_USER
          valueFrom:
            secretKeyRef:
              name: metrics
              key: username
        - name: METRICS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: metrics
              key: password
        - name: "AMPLITUDE_API_KEY"
          valueFrom:
            secretKeyRef:
              name: metrics
              key: amplitude_api_key
        - name: "AMQP_URL"
          value: "amqp://$(METRICS_USER):$(METRICS_PASSWORD)@$(RABBITMQ_SERVICE_HOST):$(RABBITMQ_SERVICE_PORT)/metrics"
        - name: "AMQP_QUEUE"
          value: "metrics"
        resources:
          limits:
            cpu: "0.1"
