FROM alpine:3.4

ENV GOPATH /go

RUN apk add -U --no-cache go git curl openssl
RUN mkdir -p /go/src/github.com/replaygaming/go-metrics

RUN mkdir -p $GOPATH/bin
ENV LGOBIN $GOPATH/bin
ENV PATH $LGOBIN:$PATH
RUN curl https://glide.sh/get | sh

WORKDIR /go/src/github.com/replaygaming/go-metrics

COPY *.go ./
COPY internal ./internal
COPY glide.lock ./
COPY glide.yaml ./

RUN glide install
RUN go install
